### PR TITLE
Detect synchronous blocks

### LINKED ISSUE #6: Incorrect stats
When I manually block the event loop for a full second with a while loop, `event-loop-stats` will still report a maximum way below that, for example 5ms. Is there something I don't understand about how to use the library? I call `eventLoopStats.sense()` every second.

### PR DESCRIPTION
**Pull request by basti1302**
This PR does two things:

* Merges downstream changes from https://github.com/ably-forks/event-loop-stats/pull/1 
* Fixes #6

The reproduction case given in #6 still didn't work after applying the changes from the ably-forks PR. That PR introduces a `previous_now` variable and the handling of that had a little issue: The fix for #6 (after applying the downstream PR) is basically not resetting `previous_now` to `maxPossibleNumber` on every `sense()` call. When we do this, we require _two_ `on_check` calls to happen between two consecutive `sense` calls. The reason is that we can obviously never calculate a duration on the first `on_check` after resetting `previous_now`.

I also actually see no good reason to reset `previous_now`. Resetting `min`, `max`, `num` & `sum` makes sense, but AFAICT there is no reason to _not_ compare the timestamp of the first `on_check` after a `sense` to the timestamp of the `on_check` call before the `sense` call.

### CODE REVIEW

**Comment by basti1302** [comment]
It seems the behaviour differs a bit between Node.js versions, I'll check the details. Consider this as WIP for now and do not merge yet.

File: src/eventLoopStats.cc [hunk 1]
```diff
@@ -6,46 +6,72 @@ const uint32_t maxPossibleNumber = 4294967295;
...
+
+// The minimum event loop duration since the last sense() call.
 uint32_t min;
+// The maximum event loop duration since the last sense() call.
 uint32_t max;
-uint32_t num;
+// The sum of event loop durations the last sense() call.
 uint32_t sum;
+// The number of event loop iterations since the last sense() call.
+uint32_t num;
```
Comment (basti1302) [inline src/eventLoopStats.cc:17]: Just resorted those a little, because I feel sum has more to do with min and max than num has.

File: src/eventLoopStats.cc [hunk 2]
```diff
@@ -6,46 +6,72 @@ const uint32_t maxPossibleNumber = 4294967295;
...
+
+uint32_t previous_now = maxPossibleNumber;
```
Comment (basti1302) [inline src/eventLoopStats.cc:19]: Init `previous_now` to `maxPossibleNumber ` only once at the start, not in every `reset`.

File: src/eventLoopStats.cc [hunk 3]
```diff
@@ -6,46 +6,72 @@ const uint32_t maxPossibleNumber = 4294967295;
...
     duration = 0;
   } else {
-    duration = now - start_time;
+    // Calculate the duration since the last on_check call - this is the
+    // event loop lag.
+    duration = now - previous_now;
   }
 
-  num += 1;
-  sum += duration;
```
Comment (basti1302) [inline src/eventLoopStats.cc:37]: also resorted, see below

**Comment by basti1302** [comment]
This is finished for now and should be an improvement over the current stats collection. But note that all of this is not a silver bullet that covers all cases, see the discussion in https://github.com/ably-forks/event-loop-stats/pull/1

**Comment by rochdev** [comment]
Opened #8 to address the limitations of the current approach.

**Comment by bripkens** [comment]
Thank you for these! ❤️ We will check these out some time this week.

**Comment by fgm** [comment]
For the record [MeteorServerInfo](https://github.com/fgm/meteor_server_info) 1.2.5 / 1.2.6 depends on this PR: I'll update it when/if the PR gets merged.

**Comment by adityapatadia** [comment]
Hi, is there any plan to merge this one?

**Comment by bripkens** [comment]
Sorry for this delay. Now merged and released as version [1.3.0](https://www.npmjs.com/package/event-loop-stats/v/1.3.0).

**Comment by adityapatadia** [comment]
Awesome!
